#!/bin/sh
#
# Copyright (C) 2014 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

CALIBRE_CONFIG="/etc/calibre-server.conf";

libraryfolder=$(omv_config_get "//services/calibre/library-folder")
port=$(omv_config_get "//services/calibre/port")
username=$(omv_config_get "//services/calibre/username")
password=$(omv_config_get "//services/calibre/password")
maxcover=$(omv_config_get "//services/calibre/maxcover")

# Create calibre config file
cat <<EOF > ${CALIBRE_CONFIG}
LIBRARY=${libraryfolder}
PORT=${port}
USERNAME=${username}
PASSWORD=${password}
MAX_COVER=${maxcover}
EXTRA_OPTS=""
EOF

if [ "$(omv_config_get "//services/calibre/enable")" != "1" ]; then
    exit 0
fi

# move data folder
calibre_home="$(getent passwd calibre | cut -d: -f6)"

if [ "${calibre_home}" != "${libraryfolder}" ]; then
    /etc/init.d/calibre stop

    if [ ! -d "${libraryfolder}" ]; then
        mkdir -p "${libraryfolder}"
    fi

    chown calibre:users "${libraryfolder}"

    if [ -d "${calibre_home}" ]; then
        touch ${calibre_home}/temp

        cp -rfp ${calibre_home}/* ${libraryfolder}/
        rm -rf ${calibre_home}
    fi

    chown -R calibre:users "${libraryfolder}"

    /usr/sbin/usermod -d "${libraryfolder}" calibre

    /etc/init.d/calibre start
fi
