#! /bin/sh

# Copyright (C) 2011- by Mar2zz <LaSi.Mar2zz@gmail.com>
# Copyright (C) 2014- by OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# released under GPL, version 2 or later

### BEGIN INIT INFO
# Provides:          Calibre server instance
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of Calibre server
# Description:       starts instance of Calibre server using start-stop-daemon
### END INIT INFO

# main variables
DAEMON=/opt/calibre/calibre-server
SETTINGS=/etc/calibre-server.conf

SETTINGS_LOADED=FALSE

NAME=Calibre

# only accept values from /etc/calibre-server.conf
unset RUN_AS LIBRARY PORT PID_FILE

. /lib/lsb/init-functions

[ -x $DAEMON ] || {
    log_warning_msg "$NAME: Can't execute daemon, aborting. See $DAEMON";
    return 1; }

[ -r $SETTINGS ] || {
    log_warning_msg "$NAME: Can't read settings, aborting. See $SETTINGS";
    return 1; }

load_settings() {
    if [ $SETTINGS_LOADED != "TRUE" ]; then
        . $SETTINGS

        DAEMON_OPTS="--daemonize"
        [ -n "$LIBRARY" ] && DAEMON_OPTS="$DAEMON_OPTS --with-library=$LIBRARY"
        [ -n "$PORT" ] && DAEMON_OPTS="$DAEMON_OPTS --port=$PORT"
        [ -n "$USERNAME" ] && DAEMON_OPTS="$DAEMON_OPTS --username=$USERNAME"
        [ -n "$PASSWORD" ] && DAEMON_OPTS="$DAEMON_OPTS --password=$PASSWORD"
        [ -n "$COVERSIZE" ] && DAEMON_OPTS="$DAEMON_OPTS --max-cover=$MAX_COVER"
        [ -n "$EXTRA_OPTS" ] && DAEMON_OPTS="DAEMON_OPTS $EXTRA_OPTS"
        [ -n "$PID_FILE" ] || PID_FILE=/var/run/calibre/calibre-server.pid
        DAEMON_OPTS="$DAEMON_OPTS --pidfile=$PID_FILE"
        SETTINGS_LOADED=TRUE
    fi
    return 0
}

load_settings || exit 0

if [ -e $PID_FILE ]; then
    PID=`cat $PID_FILE`
    if ! kill -0 $PID > /dev/null 2>&1; then
        echo "Removing stale $PID_FILE"
        remove_pid
    fi
fi

is_running () {
    if [ ! -e $PID_FILE ]; then
        return 1
    fi
    return 0
}

handle_pid () {
    PID_PATH=`dirname $PID_FILE`
    [ -d $PID_PATH ] || mkdir -p $PID_PATH && chown -R $RUN_AS $PID_PATH > /dev/null || {
        log_warning_msg "$NAME: Could not create $PID_FILE, aborting.";
        return 1;}
}

remove_pid () {
    if [ -e $PID_FILE ]; then
        rm -f $PID_FILE
    fi
}
start_calibre () {
    if ! is_running; then
        echo "Starting $NAME"
        handle_pid
        remove_pid
        start-stop-daemon -o -c $RUN_AS --start --pidfile $PID_FILE --exec $DAEMON -- $DAEMON_OPTS
    else
        echo "$NAME: already running (pid $PID)"
    fi
}

stop_calibre () {
    if is_running; then
        echo "Stopping $NAME"
        start-stop-daemon --stop --pidfile $PID_FILE --retry 15
    else
        echo "$NAME: not running"
    fi
    remove_pid
}

case "$1" in
    start)
        start_calibre
        ;;
    stop)
        stop_calibre
        ;;
    restart|force-reload)
        stop_calibre
        start_calibre
        ;;
    status)
        status_of_proc -p "$PID_FILE" "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0