#! /bin/sh

# Copyright (C) 2011- by Mar2zz <LaSi.Mar2zz@gmail.com>
# Copyright (C) 2014- by OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# released under GPL, version 2 or later

### BEGIN INIT INFO
# Provides:          Calibre server instance
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of Calibre server
# Description:       starts instance of Calibre server using start-stop-daemon
### END INIT INFO

# main variables
RUN_AS=calibre
RUN_GRP=users
APP_PATH=/opt/calibre
DAEMON=/opt/calibre/calibre-server
ENABLE_DAEMON=1
PID_FILE=/var/run/calibre/calibre.pid
PID_PATH=$(dirname $PID_FILE)
NAME=Calibre
DESC=Calibre
SETTINGS=/etc/calibre-server.conf

SETTINGS_LOADED=FALSE

# Get lsb functions
. /lib/lsb/init-functions

load_settings() {
    if [ $SETTINGS_LOADED != "TRUE" ]; then
        . $SETTINGS

        DAEMON_OPTS="--daemonize"
        [ -n "$LIBRARY" ] && DAEMON_OPTS="$DAEMON_OPTS --with-library=$LIBRARY"
        [ -n "$PORT" ] && DAEMON_OPTS="$DAEMON_OPTS --port=$PORT"
        [ -n "$USERNAME" ] && DAEMON_OPTS="$DAEMON_OPTS --username=$USERNAME"
        [ -n "$PASSWORD" ] && DAEMON_OPTS="$DAEMON_OPTS --password=$PASSWORD"
        [ -n "$COVERSIZE" ] && DAEMON_OPTS="$DAEMON_OPTS --max-cover=$MAX_COVER"
        [ -n "$EXTRA_OPTS" ] && DAEMON_OPTS="DAEMON_OPTS $EXTRA_OPTS"
        DAEMON_OPTS="$DAEMON_OPTS --pidfile=$PID_FILE"
        SETTINGS_LOADED=TRUE
    fi
    return 0
}

load_settings || exit 0

# Create PID directory if not exist and ensure the calibre user can write to it
if [ ! -d $PID_PATH ]; then
    mkdir -p $PID_PATH
    chown $RUN_AS $PID_PATH
fi

if [ -e $PID_FILE ]; then
    PID=`cat $PID_FILE`
    if ! kill -0 $PID > /dev/null 2>&1; then
        echo "Removing stale $PID_FILE"
        rm -f $PID_FILE
    fi
fi

is_running () {
    if [ ! -e $PID_FILE ]; then
        return 1
    fi
    return 0
}

start_calibre () {
    if ! is_running; then
        echo "Starting $DESC"
        sudo -u $RUN_AS $DAEMON $DAEMON_OPTS &> /dev/null
    else
        echo "$DESC is running"
    fi
}

stop_calibre () {
    if is_running; then
        echo "Stopping $DESC"
        start-stop-daemon --stop --pidfile $PID_FILE --retry 15
    fi
}

case "$1" in
    start)
        start_calibre
        ;;
    stop)
        stop_calibre
        ;;
    restart|force-reload)
        stop_calibre
        start_calibre
        ;;
    status)
        status_of_proc -p "$PID_FILE" "$DAEMON" "$NAME"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        ;;
esac

exit 0