#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in

    configure)
        if ! getent passwd calibre >/dev/null 2>&1;
            echo "Adding calibre user..."
            useradd --create-home --groups users --no-user-group --shell /usr/sbin/nologin calibre
        else
            echo "calibre user already exists."
        fi

        if ! omv_config_exists "/config/services/calibre"; then
            echo "Initial configuration."

            CALIBRE_HOME=$(getent passwd calibre | cut -d: -f6)

            object="<enable>0</enable>"
            object="${object}<data.sharedfolderref></data.sharedfolderref>"
            object="${object}<port>8080</port>"
            object="${object}<username></username>"
            object="${object}<password></password>"
            object="${object}<coversize></coversize>"
            object="${object}<showtab>0</showtab>"
            object="${object}<import.sharedfolderref></import.sharedfolderref>"

            omv_config_add_element "/config/services" "calibre" "${object}" true
        fi

        if [ -e /var/run/calibre ]; then
            echo "Removing old pid file..."
            rm -rf /var/run/calibre
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        omv-mkconf calibre install
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
        ;;
esac

exit 0
