#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

data_drive_to_shared_folder()
{
    local name="CalibreData"
    local comment="Calibre data location"
    local mntentref=$(omv_config_get "//services/calibre/mntentref")
    local reldirpath="calibre-data"

    # Delete old config option
    omv_config_delete "//services/calibre/mntentref"

    if [ -z "${mntentref}" ]; then
        omv_config_add_element "/config/services/calibre" "data.sharedfolderref"

        return 0
    fi

    # Prepare JSON data.
    local json="{ \"uuid\": \"undefined\", \"name\": \"${name}\", \"comment\": \"${comment}\", \"mntentref\": \"${mntentref}\", \"reldirpath\": \"${reldirpath}\" }"

    # Call omv-rcp and create the shared folder and then filter out the
    # uuid of the new shared folder.
    uuid=$(omv-rpc ShareMgmt set "${json}" | grep -Po '(?<="uuid":")[^"]*')

    # Add the shared folder to the plugin config.
    omv_config_add_element "/config/services/calibre" "data.sharedfolderref" $uuid
}

case "$1" in

    configure)

        if ! grep -q "^calibre:" /etc/passwd; then
            echo "Adding calibre user..."
            useradd --create-home --groups users --no-user-group --shell /usr/sbin/nologin calibre
        else
            echo "calibre user already exists."
        fi

        if ! omv_config_exists "/config/services/calibre"; then
            echo "Initial configuration."

            CALIBRE_HOME=$(getent passwd calibre | cut -d: -f6)

            object="<enable>0</enable>"
            object="${object}<data.sharedfolderref></data.sharedfolderref>"
            object="${object}<port>8080</port>"
            object="${object}<username></username>"
            object="${object}<password></password>"
            object="${object}<coversize></coversize>"
            object="${object}<showtab>0</showtab>"
            object="${object}<import.sharedfolderref></import.sharedfolderref>"

            omv_config_add_element "/config/services" "calibre" "${object}" true
        fi

        if [ -e /var/run/calibre ]; then
            echo "Removing old pid file..."
            rm -rf /var/run/calibre
        fi

        if dpkg --compare-versions "$2" lt-nl "1.0.4"; then
            data_drive_to_shared_folder
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        omv-mkconf calibre install
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
