#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in

    configure)
        if ! getent passwd calibre >/dev/null 2>&1; then
            echo "Adding calibre user..."
            useradd --create-home \
                    --groups users \
                    --no-user-group \
                    --shell /usr/sbin/nologin \
                    calibre
        else
            echo "calibre user already exists."
        fi

        mkdir -p /var/run/calibre
        chown calibre:users /var/run/calibre

        echo "Removing old pid file..."
        rm -f /var/run/calibre/calibre.pid

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.calibre"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.calibre" "${2}"
        fi

        omv-mkconf calibre install
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
        ;;
esac

exit 0
